// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x.proto

package com.dfire.protocol;

public final class RpcHeartBeatMessage {
  private RpcHeartBeatMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AllHeartBeatInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AllHeartBeatInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    boolean containsValues(
            String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, HeartBeatMessage>
    getValues();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    java.util.Map<String, HeartBeatMessage>
    getValuesMap();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    HeartBeatMessage getValuesOrDefault(
            String key,
            HeartBeatMessage defaultValue);
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    HeartBeatMessage getValuesOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code AllHeartBeatInfoMessage}
   */
  public  static final class AllHeartBeatInfoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AllHeartBeatInfoMessage)
      AllHeartBeatInfoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllHeartBeatInfoMessage.newBuilder() to construct.
    private AllHeartBeatInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllHeartBeatInfoMessage() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllHeartBeatInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, HeartBeatMessage>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AllHeartBeatInfoMessage.class, Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, HeartBeatMessage> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, HeartBeatMessage>newDefaultInstance(
                  RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  HeartBeatMessage.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, HeartBeatMessage> values_;
    private com.google.protobuf.MapField<String, HeartBeatMessage>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public boolean containsValues(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, HeartBeatMessage> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public java.util.Map<String, HeartBeatMessage> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public HeartBeatMessage getValuesOrDefault(
        String key,
        HeartBeatMessage defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, HeartBeatMessage> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public HeartBeatMessage getValuesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, HeartBeatMessage> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, HeartBeatMessage> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, HeartBeatMessage>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AllHeartBeatInfoMessage)) {
        return super.equals(obj);
      }
      AllHeartBeatInfoMessage other = (AllHeartBeatInfoMessage) obj;

      boolean result = true;
      result = result && internalGetValues().equals(
          other.internalGetValues());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AllHeartBeatInfoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllHeartBeatInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllHeartBeatInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllHeartBeatInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AllHeartBeatInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AllHeartBeatInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllHeartBeatInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AllHeartBeatInfoMessage)
        AllHeartBeatInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AllHeartBeatInfoMessage.class, Builder.class);
      }

      // Construct using com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableValues().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
      }

      public AllHeartBeatInfoMessage getDefaultInstanceForType() {
        return AllHeartBeatInfoMessage.getDefaultInstance();
      }

      public AllHeartBeatInfoMessage build() {
        AllHeartBeatInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AllHeartBeatInfoMessage buildPartial() {
        AllHeartBeatInfoMessage result = new AllHeartBeatInfoMessage(this);
        int from_bitField0_ = bitField0_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AllHeartBeatInfoMessage) {
          return mergeFrom((AllHeartBeatInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AllHeartBeatInfoMessage other) {
        if (other == AllHeartBeatInfoMessage.getDefaultInstance()) return this;
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AllHeartBeatInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AllHeartBeatInfoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          String, HeartBeatMessage> values_;
      private com.google.protobuf.MapField<String, HeartBeatMessage>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<String, HeartBeatMessage>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public boolean containsValues(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, HeartBeatMessage> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public java.util.Map<String, HeartBeatMessage> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public HeartBeatMessage getValuesOrDefault(
          String key,
          HeartBeatMessage defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, HeartBeatMessage> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public HeartBeatMessage getValuesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, HeartBeatMessage> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public Builder removeValues(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, HeartBeatMessage>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */
      public Builder putValues(
          String key,
          HeartBeatMessage value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public Builder putAllValues(
          java.util.Map<String, HeartBeatMessage> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AllHeartBeatInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:AllHeartBeatInfoMessage)
    private static final AllHeartBeatInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AllHeartBeatInfoMessage();
    }

    public static AllHeartBeatInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllHeartBeatInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<AllHeartBeatInfoMessage>() {
      public AllHeartBeatInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllHeartBeatInfoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllHeartBeatInfoMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AllHeartBeatInfoMessage> getParserForType() {
      return PARSER;
    }

    public AllHeartBeatInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    java.util.List<String>
        getRunningsList();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    int getRunningsCount();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    String getRunnings(int index);
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    com.google.protobuf.ByteString
        getRunningsBytes(int index);

    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    java.util.List<String>
        getDebugRunningsList();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    int getDebugRunningsCount();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    String getDebugRunnings(int index);
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    com.google.protobuf.ByteString
        getDebugRunningsBytes(int index);

    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    java.util.List<String>
        getManualRunningsList();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    int getManualRunningsCount();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    String getManualRunnings(int index);
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    com.google.protobuf.ByteString
        getManualRunningsBytes(int index);

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>float mem_rate = 5;</code>
     */
    float getMemRate();

    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    String getHost();
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>float cpu_load_per_core = 7;</code>
     */
    float getCpuLoadPerCore();

    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>float mem_total = 4096;</code>
     */
    float getMemTotal();

    /**
     * <code>int32 cores = 8;</code>
     */
    int getCores();
  }
  /**
   * Protobuf type {@code HeartBeatMessage}
   */
  public  static final class HeartBeatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatMessage)
      HeartBeatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatMessage.newBuilder() to construct.
    private HeartBeatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatMessage() {
      runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timestamp_ = 0L;
      memRate_ = 0F;
      host_ = "";
      cpuLoadPerCore_ = 0F;
      memTotal_ = 0F;
      cores_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                runnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              runnings_.add(s);
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                debugRunnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              debugRunnings_.add(s);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                manualRunnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              manualRunnings_.add(s);
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            case 45: {

              memRate_ = input.readFloat();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 61: {

              cpuLoadPerCore_ = input.readFloat();
              break;
            }
            case 64: {

              cores_ = input.readInt32();
              break;
            }
            case 32773: {

              memTotal_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = runnings_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = debugRunnings_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = manualRunnings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int RUNNINGS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList runnings_;
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRunningsList() {
      return runnings_;
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public int getRunningsCount() {
      return runnings_.size();
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public String getRunnings(int index) {
      return runnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRunningsBytes(int index) {
      return runnings_.getByteString(index);
    }

    public static final int DEBUGRUNNINGS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList debugRunnings_;
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDebugRunningsList() {
      return debugRunnings_;
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public int getDebugRunningsCount() {
      return debugRunnings_.size();
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public String getDebugRunnings(int index) {
      return debugRunnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebugRunningsBytes(int index) {
      return debugRunnings_.getByteString(index);
    }

    public static final int MANUALRUNNINGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList manualRunnings_;
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getManualRunningsList() {
      return manualRunnings_;
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public int getManualRunningsCount() {
      return manualRunnings_.size();
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public String getManualRunnings(int index) {
      return manualRunnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public com.google.protobuf.ByteString
        getManualRunningsBytes(int index) {
      return manualRunnings_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MEM_RATE_FIELD_NUMBER = 5;
    private float memRate_;
    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>float mem_rate = 5;</code>
     */
    public float getMemRate() {
      return memRate_;
    }

    public static final int HOST_FIELD_NUMBER = 6;
    private volatile Object host_;
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_LOAD_PER_CORE_FIELD_NUMBER = 7;
    private float cpuLoadPerCore_;
    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>float cpu_load_per_core = 7;</code>
     */
    public float getCpuLoadPerCore() {
      return cpuLoadPerCore_;
    }

    public static final int MEM_TOTAL_FIELD_NUMBER = 4096;
    private float memTotal_;
    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>float mem_total = 4096;</code>
     */
    public float getMemTotal() {
      return memTotal_;
    }

    public static final int CORES_FIELD_NUMBER = 8;
    private int cores_;
    /**
     * <code>int32 cores = 8;</code>
     */
    public int getCores() {
      return cores_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < runnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, runnings_.getRaw(i));
      }
      for (int i = 0; i < debugRunnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, debugRunnings_.getRaw(i));
      }
      for (int i = 0; i < manualRunnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, manualRunnings_.getRaw(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      if (memRate_ != 0F) {
        output.writeFloat(5, memRate_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, host_);
      }
      if (cpuLoadPerCore_ != 0F) {
        output.writeFloat(7, cpuLoadPerCore_);
      }
      if (cores_ != 0) {
        output.writeInt32(8, cores_);
      }
      if (memTotal_ != 0F) {
        output.writeFloat(4096, memTotal_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < runnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(runnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRunningsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < debugRunnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(debugRunnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDebugRunningsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < manualRunnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(manualRunnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getManualRunningsList().size();
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (memRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, memRate_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, host_);
      }
      if (cpuLoadPerCore_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, cpuLoadPerCore_);
      }
      if (cores_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cores_);
      }
      if (memTotal_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4096, memTotal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeartBeatMessage)) {
        return super.equals(obj);
      }
      HeartBeatMessage other = (HeartBeatMessage) obj;

      boolean result = true;
      result = result && getRunningsList()
          .equals(other.getRunningsList());
      result = result && getDebugRunningsList()
          .equals(other.getDebugRunningsList());
      result = result && getManualRunningsList()
          .equals(other.getManualRunningsList());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (
          Float.floatToIntBits(getMemRate())
          == Float.floatToIntBits(
              other.getMemRate()));
      result = result && getHost()
          .equals(other.getHost());
      result = result && (
          Float.floatToIntBits(getCpuLoadPerCore())
          == Float.floatToIntBits(
              other.getCpuLoadPerCore()));
      result = result && (
          Float.floatToIntBits(getMemTotal())
          == Float.floatToIntBits(
              other.getMemTotal()));
      result = result && (getCores()
          == other.getCores());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRunningsCount() > 0) {
        hash = (37 * hash) + RUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getRunningsList().hashCode();
      }
      if (getDebugRunningsCount() > 0) {
        hash = (37 * hash) + DEBUGRUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getDebugRunningsList().hashCode();
      }
      if (getManualRunningsCount() > 0) {
        hash = (37 * hash) + MANUALRUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getManualRunningsList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + MEM_RATE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getMemRate());
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + CPU_LOAD_PER_CORE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getCpuLoadPerCore());
      hash = (37 * hash) + MEM_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getMemTotal());
      hash = (37 * hash) + CORES_FIELD_NUMBER;
      hash = (53 * hash) + getCores();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeartBeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeartBeatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatMessage)
        HeartBeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatMessage.class, Builder.class);
      }

      // Construct using com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;

        memRate_ = 0F;

        host_ = "";

        cpuLoadPerCore_ = 0F;

        memTotal_ = 0F;

        cores_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      public HeartBeatMessage getDefaultInstanceForType() {
        return HeartBeatMessage.getDefaultInstance();
      }

      public HeartBeatMessage build() {
        HeartBeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatMessage buildPartial() {
        HeartBeatMessage result = new HeartBeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = runnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.runnings_ = runnings_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = debugRunnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.debugRunnings_ = debugRunnings_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = manualRunnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.manualRunnings_ = manualRunnings_;
        result.timestamp_ = timestamp_;
        result.memRate_ = memRate_;
        result.host_ = host_;
        result.cpuLoadPerCore_ = cpuLoadPerCore_;
        result.memTotal_ = memTotal_;
        result.cores_ = cores_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatMessage) {
          return mergeFrom((HeartBeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatMessage other) {
        if (other == HeartBeatMessage.getDefaultInstance()) return this;
        if (!other.runnings_.isEmpty()) {
          if (runnings_.isEmpty()) {
            runnings_ = other.runnings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRunningsIsMutable();
            runnings_.addAll(other.runnings_);
          }
          onChanged();
        }
        if (!other.debugRunnings_.isEmpty()) {
          if (debugRunnings_.isEmpty()) {
            debugRunnings_ = other.debugRunnings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDebugRunningsIsMutable();
            debugRunnings_.addAll(other.debugRunnings_);
          }
          onChanged();
        }
        if (!other.manualRunnings_.isEmpty()) {
          if (manualRunnings_.isEmpty()) {
            manualRunnings_ = other.manualRunnings_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureManualRunningsIsMutable();
            manualRunnings_.addAll(other.manualRunnings_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getMemRate() != 0F) {
          setMemRate(other.getMemRate());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getCpuLoadPerCore() != 0F) {
          setCpuLoadPerCore(other.getCpuLoadPerCore());
        }
        if (other.getMemTotal() != 0F) {
          setMemTotal(other.getMemTotal());
        }
        if (other.getCores() != 0) {
          setCores(other.getCores());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRunningsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = new com.google.protobuf.LazyStringArrayList(runnings_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRunningsList() {
        return runnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public int getRunningsCount() {
        return runnings_.size();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public String getRunnings(int index) {
        return runnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRunningsBytes(int index) {
        return runnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder setRunnings(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningsIsMutable();
        runnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addRunnings(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningsIsMutable();
        runnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addAllRunnings(
          Iterable<String> values) {
        ensureRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, runnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder clearRunnings() {
        runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRunningsIsMutable();
        runnings_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDebugRunningsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = new com.google.protobuf.LazyStringArrayList(debugRunnings_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDebugRunningsList() {
        return debugRunnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public int getDebugRunningsCount() {
        return debugRunnings_.size();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public String getDebugRunnings(int index) {
        return debugRunnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDebugRunningsBytes(int index) {
        return debugRunnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder setDebugRunnings(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningsIsMutable();
        debugRunnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addDebugRunnings(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningsIsMutable();
        debugRunnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addAllDebugRunnings(
          Iterable<String> values) {
        ensureDebugRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, debugRunnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder clearDebugRunnings() {
        debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addDebugRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDebugRunningsIsMutable();
        debugRunnings_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureManualRunningsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = new com.google.protobuf.LazyStringArrayList(manualRunnings_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getManualRunningsList() {
        return manualRunnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public int getManualRunningsCount() {
        return manualRunnings_.size();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public String getManualRunnings(int index) {
        return manualRunnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public com.google.protobuf.ByteString
          getManualRunningsBytes(int index) {
        return manualRunnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder setManualRunnings(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningsIsMutable();
        manualRunnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addManualRunnings(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningsIsMutable();
        manualRunnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addAllManualRunnings(
          Iterable<String> values) {
        ensureManualRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, manualRunnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder clearManualRunnings() {
        manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addManualRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureManualRunningsIsMutable();
        manualRunnings_.add(value);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float memRate_ ;
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public float getMemRate() {
        return memRate_;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public Builder setMemRate(float value) {
        
        memRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public Builder clearMemRate() {
        
        memRate_ = 0F;
        onChanged();
        return this;
      }

      private Object host_ = "";
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private float cpuLoadPerCore_ ;
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public float getCpuLoadPerCore() {
        return cpuLoadPerCore_;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public Builder setCpuLoadPerCore(float value) {
        
        cpuLoadPerCore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public Builder clearCpuLoadPerCore() {
        
        cpuLoadPerCore_ = 0F;
        onChanged();
        return this;
      }

      private float memTotal_ ;
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public float getMemTotal() {
        return memTotal_;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public Builder setMemTotal(float value) {
        
        memTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public Builder clearMemTotal() {
        
        memTotal_ = 0F;
        onChanged();
        return this;
      }

      private int cores_ ;
      /**
       * <code>int32 cores = 8;</code>
       */
      public int getCores() {
        return cores_;
      }
      /**
       * <code>int32 cores = 8;</code>
       */
      public Builder setCores(int value) {
        
        cores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cores = 8;</code>
       */
      public Builder clearCores() {
        
        cores_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatMessage)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatMessage)
    private static final HeartBeatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeartBeatMessage();
    }

    public static HeartBeatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatMessage>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatMessage>() {
      public HeartBeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HeartBeatMessage> getParserForType() {
      return PARSER;
    }

    public HeartBeatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllHeartBeatInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllHeartBeatInfoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllHeartBeatInfoMessage_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\007x.proto\"\221\001\n\027AllHeartBeatInfoMessage\0224\n" +
      "\006values\030\001 \003(\0132$.AllHeartBeatInfoMessage." +
      "ValuesEntry\032@\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022" +
      " \n\005value\030\002 \001(\0132\021.HeartBeatMessage:\0028\001\"\304\001" +
      "\n\020HeartBeatMessage\022\020\n\010runnings\030\001 \003(\t\022\025\n\r" +
      "debugRunnings\030\002 \003(\t\022\026\n\016manualRunnings\030\003 " +
      "\003(\t\022\021\n\ttimestamp\030\004 \001(\003\022\020\n\010mem_rate\030\005 \001(\002" +
      "\022\014\n\004host\030\006 \001(\t\022\031\n\021cpu_load_per_core\030\007 \001(" +
      "\002\022\022\n\tmem_total\030\200  \001(\002\022\r\n\005cores\030\010 \001(\005B+\n\022" +
      "com.dfire.protocolB\023RpcHeartBeatMessageH" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AllHeartBeatInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AllHeartBeatInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllHeartBeatInfoMessage_descriptor,
        new String[] { "Values", });
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor =
      internal_static_AllHeartBeatInfoMessage_descriptor.getNestedTypes().get(0);
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_HeartBeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatMessage_descriptor,
        new String[] { "Runnings", "DebugRunnings", "ManualRunnings", "Timestamp", "MemRate", "Host", "CpuLoadPerCore", "MemTotal", "Cores", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
