// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat_message.proto

package com.dfire.protocol;

public final class RpcHeartBeatMessage {
  private RpcHeartBeatMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AllHeartBeatInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AllHeartBeatInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
    getValues();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */
    java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
    getValuesMap();
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrDefault(
        java.lang.String key,
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage defaultValue);
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code AllHeartBeatInfoMessage}
   */
  public  static final class AllHeartBeatInfoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AllHeartBeatInfoMessage)
      AllHeartBeatInfoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllHeartBeatInfoMessage.newBuilder() to construct.
    private AllHeartBeatInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllHeartBeatInfoMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllHeartBeatInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.class, com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>newDefaultInstance(
                  com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> values_;
    private com.google.protobuf.MapField<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrDefault(
        java.lang.String key,
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
     */

    public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage)) {
        return super.equals(obj);
      }
      com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage other = (com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage) obj;

      boolean result = true;
      result = result && internalGetValues().equals(
          other.internalGetValues());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllHeartBeatInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AllHeartBeatInfoMessage)
        com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.class, com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.Builder.class);
      }

      // Construct using com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableValues().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_AllHeartBeatInfoMessage_descriptor;
      }

      public com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage getDefaultInstanceForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.getDefaultInstance();
      }

      public com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage build() {
        com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage buildPartial() {
        com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage result = new com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage(this);
        int from_bitField0_ = bitField0_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage) {
          return mergeFrom((com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage other) {
        if (other == com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage.getDefaultInstance()) return this;
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> values_;
      private com.google.protobuf.MapField<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrDefault(
          java.lang.String key,
          com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */
      public Builder putValues(
          java.lang.String key,
          com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .HeartBeatMessage&gt; values = 1;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AllHeartBeatInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:AllHeartBeatInfoMessage)
    private static final com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage();
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllHeartBeatInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<AllHeartBeatInfoMessage>() {
      public AllHeartBeatInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllHeartBeatInfoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllHeartBeatInfoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllHeartBeatInfoMessage> getParserForType() {
      return PARSER;
    }

    public com.dfire.protocol.RpcHeartBeatMessage.AllHeartBeatInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    java.util.List<java.lang.String>
        getRunningList();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    int getRunningCount();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    java.lang.String getRunning(int index);
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    com.google.protobuf.ByteString
        getRunningBytes(int index);

    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    java.util.List<java.lang.String>
        getDebugRunningList();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    int getDebugRunningCount();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    java.lang.String getDebugRunning(int index);
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    com.google.protobuf.ByteString
        getDebugRunningBytes(int index);

    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    java.util.List<java.lang.String>
        getManualRunningList();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    int getManualRunningCount();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    java.lang.String getManualRunning(int index);
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    com.google.protobuf.ByteString
        getManualRunningBytes(int index);

    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    java.util.List<java.lang.String>
        getRerunRunningList();
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    int getRerunRunningCount();
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    java.lang.String getRerunRunning(int index);
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    com.google.protobuf.ByteString
        getRerunRunningBytes(int index);

    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    java.util.List<java.lang.String>
        getSuperRunningList();
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    int getSuperRunningCount();
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    java.lang.String getSuperRunning(int index);
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    com.google.protobuf.ByteString
        getSuperRunningBytes(int index);

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>float mem_rate = 5;</code>
     */
    float getMemRate();

    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>float cpu_load_per_core = 7;</code>
     */
    float getCpuLoadPerCore();

    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>float mem_total = 4096;</code>
     */
    float getMemTotal();

    /**
     * <code>int32 cores = 8;</code>
     */
    int getCores();
  }
  /**
   * Protobuf type {@code HeartBeatMessage}
   */
  public  static final class HeartBeatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatMessage)
      HeartBeatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatMessage.newBuilder() to construct.
    private HeartBeatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatMessage() {
      running_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      debugRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      manualRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      rerunRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      superRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timestamp_ = 0L;
      memRate_ = 0F;
      host_ = "";
      cpuLoadPerCore_ = 0F;
      memTotal_ = 0F;
      cores_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                running_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              running_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                debugRunning_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              debugRunning_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                manualRunning_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              manualRunning_.add(s);
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            case 45: {

              memRate_ = input.readFloat();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 61: {

              cpuLoadPerCore_ = input.readFloat();
              break;
            }
            case 64: {

              cores_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                rerunRunning_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              rerunRunning_.add(s);
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                superRunning_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              superRunning_.add(s);
              break;
            }
            case 32773: {

              memTotal_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          running_ = running_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunning_ = debugRunning_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunning_ = manualRunning_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          rerunRunning_ = rerunRunning_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          superRunning_ = superRunning_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.class, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.Builder.class);
    }

    private int bitField0_;
    public static final int RUNNING_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList running_;
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRunningList() {
      return running_;
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    public int getRunningCount() {
      return running_.size();
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    public java.lang.String getRunning(int index) {
      return running_.get(index);
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string running = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRunningBytes(int index) {
      return running_.getByteString(index);
    }

    public static final int DEBUGRUNNING_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList debugRunning_;
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDebugRunningList() {
      return debugRunning_;
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    public int getDebugRunningCount() {
      return debugRunning_.size();
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    public java.lang.String getDebugRunning(int index) {
      return debugRunning_.get(index);
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunning = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebugRunningBytes(int index) {
      return debugRunning_.getByteString(index);
    }

    public static final int MANUALRUNNING_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList manualRunning_;
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getManualRunningList() {
      return manualRunning_;
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    public int getManualRunningCount() {
      return manualRunning_.size();
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    public java.lang.String getManualRunning(int index) {
      return manualRunning_.get(index);
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunning = 3;</code>
     */
    public com.google.protobuf.ByteString
        getManualRunningBytes(int index) {
      return manualRunning_.getByteString(index);
    }

    public static final int RERUNRUNNING_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList rerunRunning_;
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRerunRunningList() {
      return rerunRunning_;
    }
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    public int getRerunRunningCount() {
      return rerunRunning_.size();
    }
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    public java.lang.String getRerunRunning(int index) {
      return rerunRunning_.get(index);
    }
    /**
     * <pre>
     *正在运行的重跑任务列表
     * </pre>
     *
     * <code>repeated string rerunRunning = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRerunRunningBytes(int index) {
      return rerunRunning_.getByteString(index);
    }

    public static final int SUPERRUNNING_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList superRunning_;
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSuperRunningList() {
      return superRunning_;
    }
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    public int getSuperRunningCount() {
      return superRunning_.size();
    }
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    public java.lang.String getSuperRunning(int index) {
      return superRunning_.get(index);
    }
    /**
     * <pre>
     *正在运行的超级恢复任务列表
     * </pre>
     *
     * <code>repeated string superRunning = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSuperRunningBytes(int index) {
      return superRunning_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MEM_RATE_FIELD_NUMBER = 5;
    private float memRate_;
    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>float mem_rate = 5;</code>
     */
    public float getMemRate() {
      return memRate_;
    }

    public static final int HOST_FIELD_NUMBER = 6;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>string host = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_LOAD_PER_CORE_FIELD_NUMBER = 7;
    private float cpuLoadPerCore_;
    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>float cpu_load_per_core = 7;</code>
     */
    public float getCpuLoadPerCore() {
      return cpuLoadPerCore_;
    }

    public static final int MEM_TOTAL_FIELD_NUMBER = 4096;
    private float memTotal_;
    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>float mem_total = 4096;</code>
     */
    public float getMemTotal() {
      return memTotal_;
    }

    public static final int CORES_FIELD_NUMBER = 8;
    private int cores_;
    /**
     * <code>int32 cores = 8;</code>
     */
    public int getCores() {
      return cores_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < running_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, running_.getRaw(i));
      }
      for (int i = 0; i < debugRunning_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, debugRunning_.getRaw(i));
      }
      for (int i = 0; i < manualRunning_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, manualRunning_.getRaw(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      if (memRate_ != 0F) {
        output.writeFloat(5, memRate_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, host_);
      }
      if (cpuLoadPerCore_ != 0F) {
        output.writeFloat(7, cpuLoadPerCore_);
      }
      if (cores_ != 0) {
        output.writeInt32(8, cores_);
      }
      for (int i = 0; i < rerunRunning_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, rerunRunning_.getRaw(i));
      }
      for (int i = 0; i < superRunning_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, superRunning_.getRaw(i));
      }
      if (memTotal_ != 0F) {
        output.writeFloat(4096, memTotal_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < running_.size(); i++) {
          dataSize += computeStringSizeNoTag(running_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRunningList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < debugRunning_.size(); i++) {
          dataSize += computeStringSizeNoTag(debugRunning_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDebugRunningList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < manualRunning_.size(); i++) {
          dataSize += computeStringSizeNoTag(manualRunning_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getManualRunningList().size();
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (memRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, memRate_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, host_);
      }
      if (cpuLoadPerCore_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, cpuLoadPerCore_);
      }
      if (cores_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cores_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rerunRunning_.size(); i++) {
          dataSize += computeStringSizeNoTag(rerunRunning_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRerunRunningList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < superRunning_.size(); i++) {
          dataSize += computeStringSizeNoTag(superRunning_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSuperRunningList().size();
      }
      if (memTotal_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4096, memTotal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage)) {
        return super.equals(obj);
      }
      com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage other = (com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) obj;

      boolean result = true;
      result = result && getRunningList()
          .equals(other.getRunningList());
      result = result && getDebugRunningList()
          .equals(other.getDebugRunningList());
      result = result && getManualRunningList()
          .equals(other.getManualRunningList());
      result = result && getRerunRunningList()
          .equals(other.getRerunRunningList());
      result = result && getSuperRunningList()
          .equals(other.getSuperRunningList());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (
          java.lang.Float.floatToIntBits(getMemRate())
          == java.lang.Float.floatToIntBits(
              other.getMemRate()));
      result = result && getHost()
          .equals(other.getHost());
      result = result && (
          java.lang.Float.floatToIntBits(getCpuLoadPerCore())
          == java.lang.Float.floatToIntBits(
              other.getCpuLoadPerCore()));
      result = result && (
          java.lang.Float.floatToIntBits(getMemTotal())
          == java.lang.Float.floatToIntBits(
              other.getMemTotal()));
      result = result && (getCores()
          == other.getCores());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRunningCount() > 0) {
        hash = (37 * hash) + RUNNING_FIELD_NUMBER;
        hash = (53 * hash) + getRunningList().hashCode();
      }
      if (getDebugRunningCount() > 0) {
        hash = (37 * hash) + DEBUGRUNNING_FIELD_NUMBER;
        hash = (53 * hash) + getDebugRunningList().hashCode();
      }
      if (getManualRunningCount() > 0) {
        hash = (37 * hash) + MANUALRUNNING_FIELD_NUMBER;
        hash = (53 * hash) + getManualRunningList().hashCode();
      }
      if (getRerunRunningCount() > 0) {
        hash = (37 * hash) + RERUNRUNNING_FIELD_NUMBER;
        hash = (53 * hash) + getRerunRunningList().hashCode();
      }
      if (getSuperRunningCount() > 0) {
        hash = (37 * hash) + SUPERRUNNING_FIELD_NUMBER;
        hash = (53 * hash) + getSuperRunningList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + MEM_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMemRate());
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + CPU_LOAD_PER_CORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCpuLoadPerCore());
      hash = (37 * hash) + MEM_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMemTotal());
      hash = (37 * hash) + CORES_FIELD_NUMBER;
      hash = (53 * hash) + getCores();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatMessage)
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.class, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.Builder.class);
      }

      // Construct using com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        running_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        debugRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        manualRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        rerunRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        superRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;

        memRate_ = 0F;

        host_ = "";

        cpuLoadPerCore_ = 0F;

        memTotal_ = 0F;

        cores_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstanceForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.getDefaultInstance();
      }

      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage build() {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage buildPartial() {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage result = new com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          running_ = running_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.running_ = running_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunning_ = debugRunning_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.debugRunning_ = debugRunning_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunning_ = manualRunning_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.manualRunning_ = manualRunning_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          rerunRunning_ = rerunRunning_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.rerunRunning_ = rerunRunning_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          superRunning_ = superRunning_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.superRunning_ = superRunning_;
        result.timestamp_ = timestamp_;
        result.memRate_ = memRate_;
        result.host_ = host_;
        result.cpuLoadPerCore_ = cpuLoadPerCore_;
        result.memTotal_ = memTotal_;
        result.cores_ = cores_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) {
          return mergeFrom((com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage other) {
        if (other == com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.getDefaultInstance()) return this;
        if (!other.running_.isEmpty()) {
          if (running_.isEmpty()) {
            running_ = other.running_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRunningIsMutable();
            running_.addAll(other.running_);
          }
          onChanged();
        }
        if (!other.debugRunning_.isEmpty()) {
          if (debugRunning_.isEmpty()) {
            debugRunning_ = other.debugRunning_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDebugRunningIsMutable();
            debugRunning_.addAll(other.debugRunning_);
          }
          onChanged();
        }
        if (!other.manualRunning_.isEmpty()) {
          if (manualRunning_.isEmpty()) {
            manualRunning_ = other.manualRunning_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureManualRunningIsMutable();
            manualRunning_.addAll(other.manualRunning_);
          }
          onChanged();
        }
        if (!other.rerunRunning_.isEmpty()) {
          if (rerunRunning_.isEmpty()) {
            rerunRunning_ = other.rerunRunning_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRerunRunningIsMutable();
            rerunRunning_.addAll(other.rerunRunning_);
          }
          onChanged();
        }
        if (!other.superRunning_.isEmpty()) {
          if (superRunning_.isEmpty()) {
            superRunning_ = other.superRunning_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSuperRunningIsMutable();
            superRunning_.addAll(other.superRunning_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getMemRate() != 0F) {
          setMemRate(other.getMemRate());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getCpuLoadPerCore() != 0F) {
          setCpuLoadPerCore(other.getCpuLoadPerCore());
        }
        if (other.getMemTotal() != 0F) {
          setMemTotal(other.getMemTotal());
        }
        if (other.getCores() != 0) {
          setCores(other.getCores());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList running_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRunningIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          running_ = new com.google.protobuf.LazyStringArrayList(running_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRunningList() {
        return running_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public int getRunningCount() {
        return running_.size();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public java.lang.String getRunning(int index) {
        return running_.get(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRunningBytes(int index) {
        return running_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public Builder setRunning(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningIsMutable();
        running_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public Builder addRunning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningIsMutable();
        running_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public Builder addAllRunning(
          java.lang.Iterable<java.lang.String> values) {
        ensureRunningIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, running_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public Builder clearRunning() {
        running_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string running = 1;</code>
       */
      public Builder addRunningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRunningIsMutable();
        running_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList debugRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDebugRunningIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunning_ = new com.google.protobuf.LazyStringArrayList(debugRunning_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDebugRunningList() {
        return debugRunning_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public int getDebugRunningCount() {
        return debugRunning_.size();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public java.lang.String getDebugRunning(int index) {
        return debugRunning_.get(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDebugRunningBytes(int index) {
        return debugRunning_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public Builder setDebugRunning(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningIsMutable();
        debugRunning_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public Builder addDebugRunning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningIsMutable();
        debugRunning_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public Builder addAllDebugRunning(
          java.lang.Iterable<java.lang.String> values) {
        ensureDebugRunningIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, debugRunning_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public Builder clearDebugRunning() {
        debugRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunning = 2;</code>
       */
      public Builder addDebugRunningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDebugRunningIsMutable();
        debugRunning_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList manualRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureManualRunningIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunning_ = new com.google.protobuf.LazyStringArrayList(manualRunning_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getManualRunningList() {
        return manualRunning_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public int getManualRunningCount() {
        return manualRunning_.size();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public java.lang.String getManualRunning(int index) {
        return manualRunning_.get(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public com.google.protobuf.ByteString
          getManualRunningBytes(int index) {
        return manualRunning_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public Builder setManualRunning(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningIsMutable();
        manualRunning_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public Builder addManualRunning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningIsMutable();
        manualRunning_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public Builder addAllManualRunning(
          java.lang.Iterable<java.lang.String> values) {
        ensureManualRunningIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, manualRunning_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public Builder clearManualRunning() {
        manualRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunning = 3;</code>
       */
      public Builder addManualRunningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureManualRunningIsMutable();
        manualRunning_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList rerunRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRerunRunningIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          rerunRunning_ = new com.google.protobuf.LazyStringArrayList(rerunRunning_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRerunRunningList() {
        return rerunRunning_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public int getRerunRunningCount() {
        return rerunRunning_.size();
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public java.lang.String getRerunRunning(int index) {
        return rerunRunning_.get(index);
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRerunRunningBytes(int index) {
        return rerunRunning_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public Builder setRerunRunning(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRerunRunningIsMutable();
        rerunRunning_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public Builder addRerunRunning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRerunRunningIsMutable();
        rerunRunning_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public Builder addAllRerunRunning(
          java.lang.Iterable<java.lang.String> values) {
        ensureRerunRunningIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rerunRunning_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public Builder clearRerunRunning() {
        rerunRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的重跑任务列表
       * </pre>
       *
       * <code>repeated string rerunRunning = 9;</code>
       */
      public Builder addRerunRunningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRerunRunningIsMutable();
        rerunRunning_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList superRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSuperRunningIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          superRunning_ = new com.google.protobuf.LazyStringArrayList(superRunning_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSuperRunningList() {
        return superRunning_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public int getSuperRunningCount() {
        return superRunning_.size();
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public java.lang.String getSuperRunning(int index) {
        return superRunning_.get(index);
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSuperRunningBytes(int index) {
        return superRunning_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public Builder setSuperRunning(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSuperRunningIsMutable();
        superRunning_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public Builder addSuperRunning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSuperRunningIsMutable();
        superRunning_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public Builder addAllSuperRunning(
          java.lang.Iterable<java.lang.String> values) {
        ensureSuperRunningIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, superRunning_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public Builder clearSuperRunning() {
        superRunning_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的超级恢复任务列表
       * </pre>
       *
       * <code>repeated string superRunning = 10;</code>
       */
      public Builder addSuperRunningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSuperRunningIsMutable();
        superRunning_.add(value);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float memRate_ ;
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public float getMemRate() {
        return memRate_;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public Builder setMemRate(float value) {
        
        memRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>float mem_rate = 5;</code>
       */
      public Builder clearMemRate() {
        
        memRate_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>string host = 6;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private float cpuLoadPerCore_ ;
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public float getCpuLoadPerCore() {
        return cpuLoadPerCore_;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public Builder setCpuLoadPerCore(float value) {
        
        cpuLoadPerCore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>float cpu_load_per_core = 7;</code>
       */
      public Builder clearCpuLoadPerCore() {
        
        cpuLoadPerCore_ = 0F;
        onChanged();
        return this;
      }

      private float memTotal_ ;
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public float getMemTotal() {
        return memTotal_;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public Builder setMemTotal(float value) {
        
        memTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>float mem_total = 4096;</code>
       */
      public Builder clearMemTotal() {
        
        memTotal_ = 0F;
        onChanged();
        return this;
      }

      private int cores_ ;
      /**
       * <code>int32 cores = 8;</code>
       */
      public int getCores() {
        return cores_;
      }
      /**
       * <code>int32 cores = 8;</code>
       */
      public Builder setCores(int value) {
        
        cores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cores = 8;</code>
       */
      public Builder clearCores() {
        
        cores_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatMessage)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatMessage)
    private static final com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage();
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatMessage>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatMessage>() {
      public HeartBeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatMessage> getParserForType() {
      return PARSER;
    }

    public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllHeartBeatInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllHeartBeatInfoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllHeartBeatInfoMessage_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030heart_beat_message.proto\"\221\001\n\027AllHeartB" +
      "eatInfoMessage\0224\n\006values\030\001 \003(\0132$.AllHear" +
      "tBeatInfoMessage.ValuesEntry\032@\n\013ValuesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022 \n\005value\030\002 \001(\0132\021.HeartB" +
      "eatMessage:\0028\001\"\355\001\n\020HeartBeatMessage\022\017\n\007r" +
      "unning\030\001 \003(\t\022\024\n\014debugRunning\030\002 \003(\t\022\025\n\rma" +
      "nualRunning\030\003 \003(\t\022\024\n\014rerunRunning\030\t \003(\t\022" +
      "\024\n\014superRunning\030\n \003(\t\022\021\n\ttimestamp\030\004 \001(\003" +
      "\022\020\n\010mem_rate\030\005 \001(\002\022\014\n\004host\030\006 \001(\t\022\031\n\021cpu_" +
      "load_per_core\030\007 \001(\002\022\022\n\tmem_total\030\200  \001(\002\022" +
      "\r\n\005cores\030\010 \001(\005B+\n\022com.dfire.protocolB\023Rp" +
      "cHeartBeatMessageH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AllHeartBeatInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AllHeartBeatInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllHeartBeatInfoMessage_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor =
      internal_static_AllHeartBeatInfoMessage_descriptor.getNestedTypes().get(0);
    internal_static_AllHeartBeatInfoMessage_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllHeartBeatInfoMessage_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_HeartBeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatMessage_descriptor,
        new java.lang.String[] { "Running", "DebugRunning", "ManualRunning", "RerunRunning", "SuperRunning", "Timestamp", "MemRate", "Host", "CpuLoadPerCore", "MemTotal", "Cores", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
