// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat_message.proto

package com.dfire.protocol;

public final class RpcHeartBeatMessage {
  private RpcHeartBeatMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    java.util.List<java.lang.String>
        getRunningsList();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    int getRunningsCount();
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    java.lang.String getRunnings(int index);
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    com.google.protobuf.ByteString
        getRunningsBytes(int index);

    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    java.util.List<java.lang.String>
        getDebugRunningsList();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    int getDebugRunningsCount();
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    java.lang.String getDebugRunnings(int index);
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    com.google.protobuf.ByteString
        getDebugRunningsBytes(int index);

    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    java.util.List<java.lang.String>
        getManualRunningsList();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    int getManualRunningsCount();
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    java.lang.String getManualRunnings(int index);
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    com.google.protobuf.ByteString
        getManualRunningsBytes(int index);

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>optional float mem_rate = 5;</code>
     */
    boolean hasMemRate();
    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>optional float mem_rate = 5;</code>
     */
    float getMemRate();

    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    boolean hasHost();
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>optional float cpu_load_per_core = 7;</code>
     */
    boolean hasCpuLoadPerCore();
    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>optional float cpu_load_per_core = 7;</code>
     */
    float getCpuLoadPerCore();

    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>optional float mem_total = 4096;</code>
     */
    boolean hasMemTotal();
    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>optional float mem_total = 4096;</code>
     */
    float getMemTotal();
  }
  /**
   * Protobuf type {@code HeartBeatMessage}
   */
  public  static final class HeartBeatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatMessage)
      HeartBeatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatMessage.newBuilder() to construct.
    private HeartBeatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatMessage() {
      runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timestamp_ = 0L;
      memRate_ = 0F;
      host_ = "";
      cpuLoadPerCore_ = 0F;
      memTotal_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                runnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              runnings_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                debugRunnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              debugRunnings_.add(bs);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                manualRunnings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              manualRunnings_.add(bs);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000002;
              memRate_ = input.readFloat();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              host_ = bs;
              break;
            }
            case 61: {
              bitField0_ |= 0x00000008;
              cpuLoadPerCore_ = input.readFloat();
              break;
            }
            case 32773: {
              bitField0_ |= 0x00000010;
              memTotal_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = runnings_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = debugRunnings_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = manualRunnings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.class, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.Builder.class);
    }

    private int bitField0_;
    public static final int RUNNINGS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList runnings_;
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRunningsList() {
      return runnings_;
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public int getRunningsCount() {
      return runnings_.size();
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public java.lang.String getRunnings(int index) {
      return runnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的自动调度job列表
     * </pre>
     *
     * <code>repeated string runnings = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRunningsBytes(int index) {
      return runnings_.getByteString(index);
    }

    public static final int DEBUGRUNNINGS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList debugRunnings_;
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDebugRunningsList() {
      return debugRunnings_;
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public int getDebugRunningsCount() {
      return debugRunnings_.size();
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public java.lang.String getDebugRunnings(int index) {
      return debugRunnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的文件脚本job列表
     * </pre>
     *
     * <code>repeated string debugRunnings = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebugRunningsBytes(int index) {
      return debugRunnings_.getByteString(index);
    }

    public static final int MANUALRUNNINGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList manualRunnings_;
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getManualRunningsList() {
      return manualRunnings_;
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public int getManualRunningsCount() {
      return manualRunnings_.size();
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public java.lang.String getManualRunnings(int index) {
      return manualRunnings_.get(index);
    }
    /**
     * <pre>
     *正在运行的手动执行job列表
     * </pre>
     *
     * <code>repeated string manualRunnings = 3;</code>
     */
    public com.google.protobuf.ByteString
        getManualRunningsBytes(int index) {
      return manualRunnings_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MEM_RATE_FIELD_NUMBER = 5;
    private float memRate_;
    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>optional float mem_rate = 5;</code>
     */
    public boolean hasMemRate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *内存占用比例
     * </pre>
     *
     * <code>optional float mem_rate = 5;</code>
     */
    public float getMemRate() {
      return memRate_;
    }

    public static final int HOST_FIELD_NUMBER = 6;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送心跳的主机
     * </pre>
     *
     * <code>optional string host = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_LOAD_PER_CORE_FIELD_NUMBER = 7;
    private float cpuLoadPerCore_;
    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>optional float cpu_load_per_core = 7;</code>
     */
    public boolean hasCpuLoadPerCore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *每个核心的cpu负载
     * </pre>
     *
     * <code>optional float cpu_load_per_core = 7;</code>
     */
    public float getCpuLoadPerCore() {
      return cpuLoadPerCore_;
    }

    public static final int MEM_TOTAL_FIELD_NUMBER = 4096;
    private float memTotal_;
    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>optional float mem_total = 4096;</code>
     */
    public boolean hasMemTotal() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *总内存大小，默认4096M
     * </pre>
     *
     * <code>optional float mem_total = 4096;</code>
     */
    public float getMemTotal() {
      return memTotal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < runnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, runnings_.getRaw(i));
      }
      for (int i = 0; i < debugRunnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, debugRunnings_.getRaw(i));
      }
      for (int i = 0; i < manualRunnings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, manualRunnings_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(5, memRate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, host_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(7, cpuLoadPerCore_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(4096, memTotal_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < runnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(runnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRunningsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < debugRunnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(debugRunnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDebugRunningsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < manualRunnings_.size(); i++) {
          dataSize += computeStringSizeNoTag(manualRunnings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getManualRunningsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, memRate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, host_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, cpuLoadPerCore_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4096, memTotal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage)) {
        return super.equals(obj);
      }
      com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage other = (com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) obj;

      boolean result = true;
      result = result && getRunningsList()
          .equals(other.getRunningsList());
      result = result && getDebugRunningsList()
          .equals(other.getDebugRunningsList());
      result = result && getManualRunningsList()
          .equals(other.getManualRunningsList());
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasMemRate() == other.hasMemRate());
      if (hasMemRate()) {
        result = result && (
            java.lang.Float.floatToIntBits(getMemRate())
            == java.lang.Float.floatToIntBits(
                other.getMemRate()));
      }
      result = result && (hasHost() == other.hasHost());
      if (hasHost()) {
        result = result && getHost()
            .equals(other.getHost());
      }
      result = result && (hasCpuLoadPerCore() == other.hasCpuLoadPerCore());
      if (hasCpuLoadPerCore()) {
        result = result && (
            java.lang.Float.floatToIntBits(getCpuLoadPerCore())
            == java.lang.Float.floatToIntBits(
                other.getCpuLoadPerCore()));
      }
      result = result && (hasMemTotal() == other.hasMemTotal());
      if (hasMemTotal()) {
        result = result && (
            java.lang.Float.floatToIntBits(getMemTotal())
            == java.lang.Float.floatToIntBits(
                other.getMemTotal()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRunningsCount() > 0) {
        hash = (37 * hash) + RUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getRunningsList().hashCode();
      }
      if (getDebugRunningsCount() > 0) {
        hash = (37 * hash) + DEBUGRUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getDebugRunningsList().hashCode();
      }
      if (getManualRunningsCount() > 0) {
        hash = (37 * hash) + MANUALRUNNINGS_FIELD_NUMBER;
        hash = (53 * hash) + getManualRunningsList().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasMemRate()) {
        hash = (37 * hash) + MEM_RATE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getMemRate());
      }
      if (hasHost()) {
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
      }
      if (hasCpuLoadPerCore()) {
        hash = (37 * hash) + CPU_LOAD_PER_CORE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCpuLoadPerCore());
      }
      if (hasMemTotal()) {
        hash = (37 * hash) + MEM_TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getMemTotal());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatMessage)
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.class, com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.Builder.class);
      }

      // Construct using com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        memRate_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cpuLoadPerCore_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        memTotal_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.internal_static_HeartBeatMessage_descriptor;
      }

      @java.lang.Override
      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstanceForType() {
        return com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage build() {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage buildPartial() {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage result = new com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = runnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.runnings_ = runnings_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = debugRunnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.debugRunnings_ = debugRunnings_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = manualRunnings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.manualRunnings_ = manualRunnings_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000002;
        }
        result.memRate_ = memRate_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000004;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cpuLoadPerCore_ = cpuLoadPerCore_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000010;
        }
        result.memTotal_ = memTotal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) {
          return mergeFrom((com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage other) {
        if (other == com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage.getDefaultInstance()) return this;
        if (!other.runnings_.isEmpty()) {
          if (runnings_.isEmpty()) {
            runnings_ = other.runnings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRunningsIsMutable();
            runnings_.addAll(other.runnings_);
          }
          onChanged();
        }
        if (!other.debugRunnings_.isEmpty()) {
          if (debugRunnings_.isEmpty()) {
            debugRunnings_ = other.debugRunnings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDebugRunningsIsMutable();
            debugRunnings_.addAll(other.debugRunnings_);
          }
          onChanged();
        }
        if (!other.manualRunnings_.isEmpty()) {
          if (manualRunnings_.isEmpty()) {
            manualRunnings_ = other.manualRunnings_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureManualRunningsIsMutable();
            manualRunnings_.addAll(other.manualRunnings_);
          }
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasMemRate()) {
          setMemRate(other.getMemRate());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000020;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasCpuLoadPerCore()) {
          setCpuLoadPerCore(other.getCpuLoadPerCore());
        }
        if (other.hasMemTotal()) {
          setMemTotal(other.getMemTotal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRunningsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          runnings_ = new com.google.protobuf.LazyStringArrayList(runnings_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRunningsList() {
        return runnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public int getRunningsCount() {
        return runnings_.size();
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public java.lang.String getRunnings(int index) {
        return runnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRunningsBytes(int index) {
        return runnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder setRunnings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningsIsMutable();
        runnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addRunnings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningsIsMutable();
        runnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addAllRunnings(
          java.lang.Iterable<java.lang.String> values) {
        ensureRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, runnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder clearRunnings() {
        runnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的自动调度job列表
       * </pre>
       *
       * <code>repeated string runnings = 1;</code>
       */
      public Builder addRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRunningsIsMutable();
        runnings_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDebugRunningsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          debugRunnings_ = new com.google.protobuf.LazyStringArrayList(debugRunnings_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDebugRunningsList() {
        return debugRunnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public int getDebugRunningsCount() {
        return debugRunnings_.size();
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public java.lang.String getDebugRunnings(int index) {
        return debugRunnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDebugRunningsBytes(int index) {
        return debugRunnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder setDebugRunnings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningsIsMutable();
        debugRunnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addDebugRunnings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningsIsMutable();
        debugRunnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addAllDebugRunnings(
          java.lang.Iterable<java.lang.String> values) {
        ensureDebugRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, debugRunnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder clearDebugRunnings() {
        debugRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的文件脚本job列表
       * </pre>
       *
       * <code>repeated string debugRunnings = 2;</code>
       */
      public Builder addDebugRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDebugRunningsIsMutable();
        debugRunnings_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureManualRunningsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          manualRunnings_ = new com.google.protobuf.LazyStringArrayList(manualRunnings_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getManualRunningsList() {
        return manualRunnings_.getUnmodifiableView();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public int getManualRunningsCount() {
        return manualRunnings_.size();
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public java.lang.String getManualRunnings(int index) {
        return manualRunnings_.get(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public com.google.protobuf.ByteString
          getManualRunningsBytes(int index) {
        return manualRunnings_.getByteString(index);
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder setManualRunnings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningsIsMutable();
        manualRunnings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addManualRunnings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningsIsMutable();
        manualRunnings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addAllManualRunnings(
          java.lang.Iterable<java.lang.String> values) {
        ensureManualRunningsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, manualRunnings_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder clearManualRunnings() {
        manualRunnings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在运行的手动执行job列表
       * </pre>
       *
       * <code>repeated string manualRunnings = 3;</code>
       */
      public Builder addManualRunningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureManualRunningsIsMutable();
        manualRunnings_.add(value);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float memRate_ ;
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>optional float mem_rate = 5;</code>
       */
      public boolean hasMemRate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>optional float mem_rate = 5;</code>
       */
      public float getMemRate() {
        return memRate_;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>optional float mem_rate = 5;</code>
       */
      public Builder setMemRate(float value) {
        bitField0_ |= 0x00000010;
        memRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内存占用比例
       * </pre>
       *
       * <code>optional float mem_rate = 5;</code>
       */
      public Builder clearMemRate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        memRate_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送心跳的主机
       * </pre>
       *
       * <code>optional string host = 6;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
        return this;
      }

      private float cpuLoadPerCore_ ;
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>optional float cpu_load_per_core = 7;</code>
       */
      public boolean hasCpuLoadPerCore() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>optional float cpu_load_per_core = 7;</code>
       */
      public float getCpuLoadPerCore() {
        return cpuLoadPerCore_;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>optional float cpu_load_per_core = 7;</code>
       */
      public Builder setCpuLoadPerCore(float value) {
        bitField0_ |= 0x00000040;
        cpuLoadPerCore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每个核心的cpu负载
       * </pre>
       *
       * <code>optional float cpu_load_per_core = 7;</code>
       */
      public Builder clearCpuLoadPerCore() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cpuLoadPerCore_ = 0F;
        onChanged();
        return this;
      }

      private float memTotal_ ;
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>optional float mem_total = 4096;</code>
       */
      public boolean hasMemTotal() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>optional float mem_total = 4096;</code>
       */
      public float getMemTotal() {
        return memTotal_;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>optional float mem_total = 4096;</code>
       */
      public Builder setMemTotal(float value) {
        bitField0_ |= 0x00000080;
        memTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总内存大小，默认4096M
       * </pre>
       *
       * <code>optional float mem_total = 4096;</code>
       */
      public Builder clearMemTotal() {
        bitField0_ = (bitField0_ & ~0x00000080);
        memTotal_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatMessage)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatMessage)
    private static final com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage();
    }

    public static com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeatMessage>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatMessage>() {
      @java.lang.Override
      public HeartBeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dfire.protocol.RpcHeartBeatMessage.HeartBeatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030heart_beat_message.proto\"\265\001\n\020HeartBeat" +
      "Message\022\020\n\010runnings\030\001 \003(\t\022\025\n\rdebugRunnin" +
      "gs\030\002 \003(\t\022\026\n\016manualRunnings\030\003 \003(\t\022\021\n\ttime" +
      "stamp\030\004 \001(\003\022\020\n\010mem_rate\030\005 \001(\002\022\014\n\004host\030\006 " +
      "\001(\t\022\031\n\021cpu_load_per_core\030\007 \001(\002\022\022\n\tmem_to" +
      "tal\030\200  \001(\002B+\n\022com.dfire.protocolB\023RpcHea" +
      "rtBeatMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatMessage_descriptor,
        new java.lang.String[] { "Runnings", "DebugRunnings", "ManualRunnings", "Timestamp", "MemRate", "Host", "CpuLoadPerCore", "MemTotal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
