// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_operate.proto

package com.dfire.protocol;

public final class RpcWebOperate {
  private RpcWebOperate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code WebOperate}
   */
  public enum WebOperate
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *更新job
     * </pre>
     *
     * <code>UpdateJob = 1;</code>
     */
    UpdateJob(1),
    /**
     * <pre>
     *手动执行或者手动恢复job
     * </pre>
     *
     * <code>ExecuteJob = 2;</code>
     */
    ExecuteJob(2),
    /**
     * <pre>
     *手动取消任务
     * </pre>
     *
     * <code>CancelJob = 3;</code>
     */
    CancelJob(3),
    /**
     * <pre>
     *调试任务
     * </pre>
     *
     * <code>ExecuteDebug = 4;</code>
     */
    ExecuteDebug(4),
    /**
     * <pre>
     *生成版本
     * </pre>
     *
     * <code>GenerateAction = 5;</code>
     */
    GenerateAction(5),
    ;

    /**
     * <pre>
     *更新job
     * </pre>
     *
     * <code>UpdateJob = 1;</code>
     */
    public static final int UpdateJob_VALUE = 1;
    /**
     * <pre>
     *手动执行或者手动恢复job
     * </pre>
     *
     * <code>ExecuteJob = 2;</code>
     */
    public static final int ExecuteJob_VALUE = 2;
    /**
     * <pre>
     *手动取消任务
     * </pre>
     *
     * <code>CancelJob = 3;</code>
     */
    public static final int CancelJob_VALUE = 3;
    /**
     * <pre>
     *调试任务
     * </pre>
     *
     * <code>ExecuteDebug = 4;</code>
     */
    public static final int ExecuteDebug_VALUE = 4;
    /**
     * <pre>
     *生成版本
     * </pre>
     *
     * <code>GenerateAction = 5;</code>
     */
    public static final int GenerateAction_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WebOperate valueOf(int value) {
      return forNumber(value);
    }

    public static WebOperate forNumber(int value) {
      switch (value) {
        case 1: return UpdateJob;
        case 2: return ExecuteJob;
        case 3: return CancelJob;
        case 4: return ExecuteDebug;
        case 5: return GenerateAction;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WebOperate>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WebOperate> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WebOperate>() {
            public WebOperate findValueByNumber(int number) {
              return WebOperate.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dfire.protocol.RpcWebOperate.getDescriptor().getEnumTypes().get(0);
    }

    private static final WebOperate[] VALUES = values();

    public static WebOperate valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private WebOperate(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WebOperate)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021web_operate.proto*`\n\nWebOperate\022\r\n\tUpd" +
      "ateJob\020\001\022\016\n\nExecuteJob\020\002\022\r\n\tCancelJob\020\003\022" +
      "\020\n\014ExecuteDebug\020\004\022\022\n\016GenerateAction\020\005B%\n" +
      "\022com.dfire.protocolB\rRpcWebOperateH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
